sudo: false
language: python
env:
  - DJANGO=2.0 TEST_DIR=jalali_test
  - DJANGO=2.0.2 TEST_DIR=jalali_test
  - DJANGO=2.2.3 TEST_DIR=jalali_test
  - DJANGO=2.2.6 TEST_DIR=jalali_test
python:
  - 3.4
  - 3.6
  - 3.7
jobs:
  exclude:
  - python: 3.4
    env: DJANGO=2.2.3 TEST_DIR=jalali_test
  - python: 3.4
    env: DJANGO=2.2.6 TEST_DIR=jalali_test
  include:
  - stage: Flake8
    env:
    python: 3.7
    install: pip install flake8
    script: flake8
install:
  - pip install -q Django==$DJANGO
  - pip install jdatetime pytz
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - cd $TEST_DIR
  - python manage.py test
  - cd ..
  - python setup.py sdist
  - pip install dist/django-jalali*
