sudo: false
language: python
env:
  - DJANGO=1.8.8
python:
  - "2.7"
install:
  - pip install -q Django==$DJANGO
  - pip install jdatetime
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/django-jalali
script:
  - echo $PYTHONPATH
  - cd jalali_test/ && python manage.py test
