sudo: false
language: python
env:
  - DJANGO=1.7.11
  - DJANGO=1.8.8
  - DJANGO=1.9.0
  - DJANGO=1.9.1
  - DJANGO=1.9.5
  - DJANGO=1.10
  - DJANGO=2.0
python:
  - "2.7"
  - "3.4"
  - "3.6"
install:
  - pip install -q Django==$DJANGO
  - pip install jdatetime
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - ./run_tests.bash
